application: organic-duality-605
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: gensite.application

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest

env_variables:
  CACHE_ENABLED: true
